export let products = [
    {
        title: "Rings",
        color: ["white", "gold", "silver", "blue"],
        liked: false, 
        price: 231, 
        author: "Emilia Clarck", 
        tags: ["ring", "rings", "jewelry"], 
        info: "pretty rings", 
        photo: "picsProducts/pic0.jpg", 
        size: "small",
        tobasket: false
    },
    {
        title: "Cups",
        color: ["white"],
        like: false, 
        price: 44, 
        author: "Leyton Aldred", 
        tags: ["cup", "cups", "dishes"], 
        info: "pretty cups", 
        photo: "picsProducts/pic1.jpg", 
        size: "small",
        tobasket: false
    },
    {
        title: "Sweater",
        color: ["white", "pink", "red"],
        liked: false, 
        price: 500, 
        author: "Georgina Russell", 
        tags: ["sweater", "cardigan", "clothes"], 
        info: "pretty sweater with strawberry", 
        photo: "picsProducts/pic2.jpg", 
        size: "middle",
        tobasket: false
    },
    {
        title: "Socks",
        color: ["white", "beidge"],
        liked: false, 
        price: 23, 
        author: "Archibald Munoz", 
        tags: ["socks", "clothes"], 
        info: "pretty socks", 
        photo: "picsProducts/pic3.jpg", 
        size: "small",
        tobasket: false
    },
    {
        title: "Bag",
        color: ["blue", "yellow"],
        liked: false, 
        price: 230, 
        author: "Laith Meyer", 
        tags: ["bag", "bags", "shop"], 
        info: "pretty bags", 
        photo: "picsProducts/pic4.jpg", 
        size: "oneSize",
        tobasket: false
    },
    {
        title: "Rings",
        color: ["gold"],
        liked: false, 
        price: 10, 
        author: "Adriana Pitts", 
        tags: ["ring", "rings", "jewelry"], 
        info: "pretty gold rings", 
        photo: "picsProducts/pic5.jpg", 
        size: "small",
        tobasket: false
    },
    {
        title: "Necklace",
        color: ["white", "white", "silver", "blue", "pink"],
        liked: false, 
        price: 231, 
        author: "Shola Dickson", 
        tags: ["necklace", "jewelry"], 
        info: "pretty necklace", 
        photo: "picsProducts/pic6.jpg", 
        size: "oneSize",
        tobasket: false
    },
    {
        title: "Cup",
        color: ["white", "gold", "silver"],
        liked: false, 
        price: 200, 
        author: "Sama Daniel", 
        tags: ["ring", "rings", "jewelry"], 
        info: "pretty cups", 
        photo: "picsProducts/pic7.jpg", 
        size: "oneSize",
        tobasket: false
    },
    {
        title: "Toy",
        color: ["white", "beidge", "yellow", "blue"],
        liked: false, 
        price: 50, 
        author: "Emilia Clarck", 
        tags: ["child", "children", "kitchen"], 
        info: "pretty rings", 
        photo: "picsProducts/pic8.jpg", 
        size: "oneSize",
        tobasket: false
    },
    {
        title: "Toy",
        color: ["white", "grey", "silver", "blue"],
        liked: false, 
        price: 70, 
        author: "Jorja Bone", 
        tags: ["toy", "child", "children", "deco", "toys"], 
        info: "pretty rings", 
        photo: "picsProducts/pic9.jpg", 
        size: "oneSize",
        tobasket: false
    },
    {
        title: "Shawl",
        color: ["white", "pink", "black", "green"],
        liked: false, 
        price: 111, 
        author: "Baxter Sullivan", 
        tags: ["shawl", "clothes", "accessories"], 
        info: "pretty shawl", 
        photo: "picsProducts/pic10.jpg", 
        size: "oneSize",
        tobasket: false
    },
    {
        title: "Bag",
        color: ["white", "grey"],
        liked: false, 
        price: 23, 
        author: "Carlo Jarvis", 
        tags: ["bag", "accessories"], 
        info: "pretty bag with rabbit", 
        photo: "picsProducts/pic11.jpg", 
        size: "small",
        tobasket: false
    },
    {
        title: "Candle",
        color: ["white", "blue"],
        liked: false, 
        price: 250, 
        author: "Amalia Lyon", 
        tags: ["candle", "deco"], 
        info: "pretty candles", 
        photo: "picsProducts/pic12.jpg", 
        size: "oneSize",
        tobasket: false
    },
    {
        title: "Stand",
        color: ["white", "beidge", "green"],
        liked: false, 
        price: 231, 
        author: "Clayton Sparrow", 
        tags: ["plate", "dish", "dishes", "kitchen"], 
        info: "pretty plates", 
        photo: "picsProducts/pic13.jpg", 
        size: "oneSize",
        tobasket: false
    },
    {
        title: "Stand",
        color: ["beidge", "brown"],
        liked: false, 
        price: 40, 
        author: "Tea Walsh", 
        tags: ["stand", "deco"], 
        info: "pretty stand", 
        photo: "picsProducts/pic14.jpg", 
        size: "oneSize",
        tobasket: false
    },
    {
        title: "Sweater",
        color: ["beidge", "brown"],
        liked: false, 
        price: 500, 
        author: "Parris Santos", 
        tags: ["sweater", "cardigan", "clothes"], 
        info: "pretty cardigan", 
        photo: "picsProducts/pic15.jpg", 
        size: "medium",
        tobasket: false
    },
    {
        title: "Socks",
        color: ["white", "green"],
        liked: false, 
        price: 22, 
        author: "Oakley Hughes", 
        tags: ["socks", "clothes"], 
        info: "pretty socks", 
        photo: "picsProducts/pic16.jpg", 
        size: "oneSize",
        tobasket: false
    },
    {
        title: "Painting",
        color: ["beidge", "blue", "yellow"],
        liked: false, 
        price: 555, 
        author: "Sophia-Rose Summers", 
        tags: ["painting", "art", "deco"], 
        info: "pretty picture", 
        photo: "picsProducts/pic17.jpg", 
        size: "oneSize",
        tobasket: false
    },
    {
        title: "Toy",
        color: ["white", "yellow", "blown", "grey"],
        liked: false, 
        price: 16, 
        author: "Freddie Russo", 
        tags: ["toy", "children", "child", "toys"], 
        info: "pretty toy", 
        photo: "picsProducts/pic18.jpg", 
        size: "small",
        tobasket: false
    },
    {
        title: "Bag",
        color: ["white", "green"],
        liked: false, 
        price: 222, 
        author: "Maysa Feeney", 
        tags: ["bag", "hat", "clothes", "accessories"], 
        info: "pretty hat and bag", 
        photo: "picsProducts/pic19.jpg", 
        size: "oneSize",
        tobasket: false
    }
];